# Generated by Django 5.1.4 on 2024-12-29 09:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaireBaskanligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Daire Başkanlığı',
                'verbose_name_plural': 'Daire Başkanlıkları',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('daire_baskani', 'Daire Başkanı'), ('sube_muduru', 'Şube Müdürü'), ('personel', 'Personel')], default='personel', max_length=20, verbose_name='Rol')),
                ('unvan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ünvan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('daire_baskanligi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dairebaskanligi', verbose_name='Daire Başkanlığı')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('son_tarih', models.DateField(blank=True, null=True, verbose_name='Son Tarih')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('devam_ediyor', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('atanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atanan_gorevler', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olusturulan_gorevler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Ilerleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('gorev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ilerlemeler', to='core.gorev')),
                ('kaydeden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
            ],
            options={
                'verbose_name': 'İlerleme',
                'verbose_name_plural': 'İlerlemeler',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Fotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='fotograflar/', verbose_name='Fotoğraf')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
                ('ilerleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='core.ilerleme', verbose_name='İlerleme')),
            ],
            options={
                'verbose_name': 'Fotoğraf',
                'verbose_name_plural': 'Fotoğraflar',
                'ordering': ['-yukleme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Dosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='belgeler/', verbose_name='Dosya')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
                ('ilerleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='core.ilerleme', verbose_name='İlerleme')),
            ],
            options={
                'verbose_name': 'Dosya',
                'verbose_name_plural': 'Dosyalar',
                'ordering': ['-yukleme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Proje Adı')),
                ('baslama_tarihi', models.DateField(verbose_name='Başlama Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş Tarihi')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('devam_ediyor', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı'), ('iptal_edildi', 'İptal Edildi')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('oncelik', models.CharField(choices=[('dusuk', 'Düşük'), ('normal', 'Normal'), ('yuksek', 'Yüksek'), ('kritik', 'Kritik')], default='normal', max_length=20, verbose_name='Öncelik')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('atanan_kisiler', models.ManyToManyField(blank=True, related_name='atanan_projeler', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişiler')),
                ('daire_baskanligi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeler', to='core.dairebaskanligi', verbose_name='Daire Başkanlığı')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olusturulan_projeler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.AddField(
            model_name='ilerleme',
            name='proje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ilerlemeler', to='core.proje'),
        ),
        migrations.AddField(
            model_name='gorev',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevler', to='core.proje', verbose_name='Proje'),
        ),
        migrations.CreateModel(
            name='SubeMudurlugu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('daire_baskanligi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sube_mudurlukleri', to='core.dairebaskanligi')),
            ],
            options={
                'verbose_name': 'Şube Müdürlüğü',
                'verbose_name_plural': 'Şube Müdürlükleri',
                'ordering': ['daire_baskanligi__ad', 'ad'],
                'unique_together': {('daire_baskanligi', 'ad')},
            },
        ),
        migrations.AddField(
            model_name='proje',
            name='sube_mudurlugu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeler', to='core.subemudurlugu', verbose_name='Şube Müdürlüğü'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sube_mudurlugu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subemudurlugu', verbose_name='Şube Müdürlüğü'),
        ),
    ]
