# Generated by Django 5.1.4 on 2024-12-28 22:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaireBaskanligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Daire Başkanlığı',
                'verbose_name_plural': 'Daire Başkanlıkları',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('unvan', models.CharField(choices=[('GM', 'Genel Müdür'), ('DB', 'Daire Başkanı'), ('SM', 'Şube Müdürü'), ('P', 'Personel')], max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('daire_baskanligi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dairebaskanligi')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('baslama_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('bitis_tarihi', models.DateTimeField()),
                ('oncelik', models.CharField(choices=[('Y', 'Yüksek'), ('O', 'Orta'), ('D', 'Düşük')], max_length=1)),
                ('durum', models.CharField(choices=[('Başlamadı', 'Başlamadı'), ('Devam Ediyor', 'Devam Ediyor'), ('Tamamlandı', 'Tamamlandı')], default='Başlamadı', max_length=20)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olusturulan_gorevler', to=settings.AUTH_USER_MODEL)),
                ('sorumlu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorumlu_gorevler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
            },
        ),
        migrations.CreateModel(
            name='Ilerleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('gorev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ilerlemeler', to='core.gorev')),
                ('kaydeden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İlerleme',
                'verbose_name_plural': 'İlerlemeler',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Fotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='fotograflar/')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ilerleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='core.ilerleme')),
            ],
            options={
                'verbose_name': 'Fotoğraf',
                'verbose_name_plural': 'Fotoğraflar',
            },
        ),
        migrations.CreateModel(
            name='Dosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='belgeler/')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ilerleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='core.ilerleme')),
            ],
            options={
                'verbose_name': 'Dosya',
                'verbose_name_plural': 'Dosyalar',
            },
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('baslama_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('bitis_tarihi', models.DateTimeField()),
                ('oncelik', models.CharField(choices=[('Y', 'Yüksek'), ('O', 'Orta'), ('D', 'Düşük')], max_length=1)),
                ('durum', models.CharField(choices=[('Başlamadı', 'Başlamadı'), ('Devam Ediyor', 'Devam Ediyor'), ('Tamamlandı', 'Tamamlandı')], default='Başlamadı', max_length=20)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('daire_baskanliklari', models.ManyToManyField(related_name='projeler', to='core.dairebaskanligi')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
            },
        ),
        migrations.AddField(
            model_name='ilerleme',
            name='proje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ilerlemeler', to='core.proje'),
        ),
        migrations.AddField(
            model_name='gorev',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevler', to='core.proje'),
        ),
        migrations.CreateModel(
            name='SubeMudurlugu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('daire_baskanligi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dairebaskanligi')),
            ],
            options={
                'verbose_name': 'Şube Müdürlüğü',
                'verbose_name_plural': 'Şube Müdürlükleri',
            },
        ),
        migrations.AddField(
            model_name='proje',
            name='sube_mudurlukleri',
            field=models.ManyToManyField(related_name='projeler', to='core.subemudurlugu'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sube_mudurlugu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subemudurlugu'),
        ),
    ]
