# Generated by Django 5.1.4 on 2024-12-28 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241229_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gorev',
            options={'ordering': ['-olusturulma_tarihi'], 'verbose_name': 'Görev', 'verbose_name_plural': 'Görevler'},
        ),
        migrations.AlterField(
            model_name='gorev',
            name='atanan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atanan_gorevler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='durum',
            field=models.CharField(choices=[('BASLAMADI', 'Başlamadı'), ('DEVAM', 'Devam Ediyor'), ('TAMAMLANDI', 'Tamamlandı')], default='BASLAMADI', max_length=20),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='olusturan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olusturan_gorevler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proje',
            name='durum',
            field=models.CharField(choices=[('BASLAMADI', 'Başlamadı'), ('DEVAM', 'Devam Ediyor'), ('TAMAMLANDI', 'Tamamlandı')], default='BASLAMADI', max_length=20),
        ),
    ]
