# Generated by Django 5.1.4 on 2024-12-28 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gorev_options_alter_gorev_atanan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.RemoveField(
            model_name='proje',
            name='daire_baskanliklari',
        ),
        migrations.RemoveField(
            model_name='proje',
            name='oncelik',
        ),
        migrations.RemoveField(
            model_name='proje',
            name='sube_mudurlukleri',
        ),
        migrations.AddField(
            model_name='customuser',
            name='yonetici',
            field=models.BooleanField(default=False, verbose_name='Yönetici'),
        ),
        migrations.AddField(
            model_name='gorev',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='proje',
            name='atanan_kisiler',
            field=models.ManyToManyField(blank=True, related_name='atanan_projeler', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişiler'),
        ),
        migrations.AddField(
            model_name='proje',
            name='daire_baskanligi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Daire Başkanlığı'),
        ),
        migrations.AddField(
            model_name='proje',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='proje',
            name='sube_mudurlugu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Şube Müdürlüğü'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='daire_baskanligi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Daire Başkanlığı'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sube_mudurlugu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Şube Müdürlüğü'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unvan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='atanan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atanan_gorevler', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='baslik',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='durum',
            field=models.CharField(choices=[('BASLAMADI', 'Başlamadı'), ('DEVAM', 'Devam Ediyor'), ('TAMAMLANDI', 'Tamamlandı')], default='BASLAMADI', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='olusturan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olusturulan_gorevler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevler', to='core.proje', verbose_name='Proje'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='son_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Son Tarih'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='ad',
            field=models.CharField(max_length=200, verbose_name='Proje Adı'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='baslama_tarihi',
            field=models.DateField(verbose_name='Başlama Tarihi'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='bitis_tarihi',
            field=models.DateField(verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='durum',
            field=models.CharField(choices=[('BASLAMADI', 'Başlamadı'), ('DEVAM', 'Devam Ediyor'), ('TAMAMLANDI', 'Tamamlandı')], default='BASLAMADI', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='olusturan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olusturulan_projeler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
