# Generated by Django 5.1.4 on 2024-12-28 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AlterModelOptions(
            name='dairebaskanligi',
            options={'ordering': ['ad'], 'verbose_name': 'Daire Başkanlığı', 'verbose_name_plural': 'Daire Başkanlıkları'},
        ),
        migrations.AlterModelOptions(
            name='dosya',
            options={'ordering': ['-yukleme_tarihi'], 'verbose_name': 'Dosya', 'verbose_name_plural': 'Dosyalar'},
        ),
        migrations.AlterModelOptions(
            name='fotograf',
            options={'ordering': ['-yukleme_tarihi'], 'verbose_name': 'Fotoğraf', 'verbose_name_plural': 'Fotoğraflar'},
        ),
        migrations.AlterModelOptions(
            name='proje',
            options={'ordering': ['-olusturulma_tarihi'], 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterModelOptions(
            name='subemudurlugu',
            options={'ordering': ['daire_baskanligi__ad', 'ad'], 'verbose_name': 'Şube Müdürlüğü', 'verbose_name_plural': 'Şube Müdürlükleri'},
        ),
        migrations.AlterField(
            model_name='dairebaskanligi',
            name='ad',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dosya',
            name='dosya',
            field=models.FileField(upload_to='belgeler/', verbose_name='Dosya'),
        ),
        migrations.AlterField(
            model_name='dosya',
            name='ilerleme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='core.ilerleme', verbose_name='İlerleme'),
        ),
        migrations.AlterField(
            model_name='dosya',
            name='yukleme_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='fotograf',
            name='fotograf',
            field=models.ImageField(upload_to='fotograflar/', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='fotograf',
            name='ilerleme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='core.ilerleme', verbose_name='İlerleme'),
        ),
        migrations.AlterField(
            model_name='fotograf',
            name='yukleme_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='olusturan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olusturulan_gorevler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='ilerleme',
            name='aciklama',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='ilerleme',
            name='kaydeden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden'),
        ),
        migrations.AlterField(
            model_name='ilerleme',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='olusturan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olusturulan_projeler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='subemudurlugu',
            name='daire_baskanligi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sube_mudurlukleri', to='core.dairebaskanligi'),
        ),
        migrations.AlterUniqueTogether(
            name='subemudurlugu',
            unique_together={('daire_baskanligi', 'ad')},
        ),
    ]
