# Generated by Django 5.1.4 on 2024-12-28 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='yonetici',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('daire_baskani', 'Daire Başkanı'), ('sube_muduru', 'Şube Müdürü'), ('personel', 'Personel')], default='personel', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='daire_baskanligi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dairebaskanligi', verbose_name='Daire Başkanlığı'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sube_mudurlugu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subemudurlugu', verbose_name='Şube Müdürlüğü'),
        ),
    ]
